apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}
  labels:
    {{- include "appflowy-cloud.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "appflowy-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "appflowy-cloud.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: APPFLOWY_ENVIRONMENT
              value: production
            - name: APPFLOWY_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.name }}
                  key: {{ .Values.global.secret.postgres.appflowy.databaseUrl.key }}
            - name: APPFLOWY_REDIS_URI
              value: {{ .Values.global.redis.uri }}
            - name: APPFLOWY_GOTRUE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.name }}
                  key: {{ .Values.global.secret.jwt.secret.key }}
            - name: APPFLOWY_GOTRUE_BASE_URL
              value: {{ .Values.global.gotrue.baseUrl }}
            - name: APPFLOWY_S3_CREATE_BUCKET
              value: {{ .Values.global.s3.createBucket | quote }}
            - name: APPFLOWY_S3_USE_MINIO
              value: {{ .Values.global.s3.useMinio | quote }}
            - name: APPFLOWY_S3_MINIO_URL
              value: {{ .Values.global.s3.minioUrl }}
            {{- if .Values.global.s3.accessKey }}
            - name: APPFLOWY_S3_ACCESS_KEY
              value: {{ .Values.global.s3.accessKey }}
            - name: APPFLOWY_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.name }}
                  key: {{ .Values.global.secret.s3.secret.key }}
            {{- end }}
            - name: APPFLOWY_S3_BUCKET
              value: {{ .Values.global.s3.bucket }}
            - name: APPFLOWY_S3_REGION
              value: {{ .Values.global.s3.region }}
            - name: APPFLOWY_MAILER_SMTP_HOST
              value: {{ .Values.global.smtp.host }}
            - name: APPFLOWY_MAILER_SMTP_PORT
              value: {{ .Values.global.smtp.port | quote }}
            - name: APPFLOWY_MAILER_SMTP_TLS_KIND
              value: {{ .Values.global.smtp.tlsKind }}
            - name: APPFLOWY_MAILER_SMTP_USERNAME
              value: {{ .Values.global.smtp.user }}
            - name: APPFLOWY_MAILER_SMTP_EMAIL
              value: {{ .Values.global.smtp.email }}
            - name: APPFLOWY_MAILER_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.name }}
                  key: {{ .Values.global.secret.smtp.password.key }}
            - name: APPFLOWY_ACCESS_CONTROL
              value: {{ .Values.accessControl.enabled | quote }}
            - name: APPFLOWY_COLLABORATE_REMOVE_BATCH_SIZE
              value: {{ .Values.collab.removeBatchSize | quote }}
            - name: APPFLOWY_COLLAB_GROUP_PERSISTENCE_INTERVAL
              value: {{ .Values.collab.groupPersistenceInterval | quote }}
            - name: APPFLOWY_COLLAB_GROUP_GRACE_PERIOD_SECS
              value: {{ .Values.collab.groupGracePeriodSecs | quote }}
            - name: APPFLOWY_INDEXER_ENABLED
              value: {{ if .Values.global.ai.enabled }}{{ .Values.indexer.enabled | quote }}{{ else }}"false"{{ end }}
            - name: APPFLOWY_WEB_URL
              value: {{ printf "%s://%s:%d" .Values.global.scheme .Values.global.externalHost (.Values.global.externalPort | int) }}
            {{- if .Values.global.ai.enabled }}
            - name: AI_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret.name }}
                  key: {{ .Values.global.secret.ai.openAIAPIKey.key }}
            - name: AI_SERVER_HOST
              value: {{ .Values.global.ai.host | quote }}
            - name: AI_SERVER_PORT
              value: {{ .Values.global.ai.port | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
